#!/bin/sh

CRACKLIBDIR=@libdir@/cracklib
LOG="$CRACKLIBDIR/ptest/cracklib_ptest_$(date +%Y%m%d-%H%M%S).log"

make test | while read -r line; do
    if echo "$line" | grep -q '^.*: '; then
        if grep -q "^$line\$" expected-data; then
            echo "PASS: $line"
        else
            echo "FAIL: $line"
        fi
    else
        echo "$line" # not a test output, just pass through
    fi
done | tee -a "$LOG"

PASSED=$(grep -c '^PASS: ' "$LOG")
FAILED=$(grep -c '^FAIL: ' "$LOG")
ALL=$((PASSED + FAILED))

(   echo "=== Test Summary ==="
    echo "TOTAL: $ALL"
    echo "PASSED: $PASSED"
    echo "FAILED: $FAILED"
) | tee -a "$LOG"
